Exception: Remove exception custom wrapping, limitations: - Ts: need to cast as Error to check 'name', 'message' and 'stack' - Ts: instanceof is not working, we have to compare the 'name'
Pros: better than adding several additional classes (bundle size) + maybe fixed by Kotlin soon?