Exception: Remove NoWhenBranchMatchedException and UninitializedPropertyAccessException as they will soon be removed from stdlib (flagged as warning).